### ISSUE TITLE
Incompatibility between Conda packages versions

### ISSUE THREAD

**Issue by thomasfillon** [ANR-DIADEMS/timeside-diadems#7]
Pyannote requires Panadas>=0.19 and Matplotlib>=1.5.2 which require numpy >1.10 which is not comptible with conda aubio package.

see. https://travis-ci.org/ANR-DIADEMS/timeside-diadems/jobs/214061484

Aubio has now an Pypi package.

**Comment by yomguy** [comment]
Indeed we should use the audio pypi version, but it seems to get some trouble for now: https://github.com/aubio/aubio/issues/94

**Comment by piem** [comment]
hi there! did you see that I pushed a [package for aubio to conda-forge](https://anaconda.org/conda-forge/aubio)?

**Comment by thomasfillon** [comment]
Hi Piem,

Ok that's great ! Thank you. I did not see this as I was looking at the Piem channel but it seems better to use conda-forge.
I will update the conda configuration.

Cheers,

Thomas

**Comment by piem** [comment]
i guess the old packages 0.4.2 on my channel should be removed now. doing that now.

**Comment by thomasfillon** [comment]
Fix by da5f305
